name             'rails-config-mysql'
maintainer       'Eric Vierhaus'
maintainer_email 'ejvaudio@gmail.com'
license          'All rights reserved'
description      'Installs/Configures Rails with MySQL'
long_description 'Installs/Configures Rails with nginx webserver and MySQL database'
version          '0.1.0'

depends 'mysql', '~> 6.0.21'
depends 'mysql2_chef_gem', '~> 1.0'
depends 'database'
